### ISSUE TITLE
Another possible problem with Example use 7: not all decoy reads filtered

### ISSUE THREAD

**Issue by naumenko-sa** [jwalabroad/VariantBam#16]
Hi Jeremiah @walaj !

Thanks for the great tool!

I am using it to remove reads aligned to decoy sequences in GRCh37 before feeding the alignment to variant callers in the hope that it is doing it cleaner than picard.

VarianBam successfully removes reads from the decoy with the command:
`variant file.bam -L decoy.bed -o nodecoy.bam -b -v`

And in the samtools statistics I don't see any reads aligned to decoy:
```
GL000192.1	547496	151293	12
NC_007605	171823	0	0
hs37d5	35477943	0	0
```

However, I'm still getting complaints from Manta about some reads where decoy contig is in SA tag:
```
[2019-01-04T02:54:34.313451Z] [node127.hpc4healthlocal] [10053_1] [WorkflowRunner] [ERROR] [2019-01-04T02:53:44.803768Z] [node127.hpc4healthlocal] [10053_1] [makeLocusGraph_chromId_022_X_0012] 	E00434:19:HNLMJCCXX:4:2212:16051:3313/1 tid:pos:strand 22:143507208:- cigar: 116M32S templSize: -495 sa: hs37d5,9340085,+,32M116S,60,0; mate_tid:pos:strand 22:143506829:+
```

Would it be possible to remove those reads with VariantBam?

Sergey

**Comment by walaj** [comment]
Hi Sergey,

If I understand the issue (let me know if not), VariantBam has now successfully filtered reads that have an alignment, or a pair-mate alignment, to the decoy. However, Manta is complaining about reads that have a secondary alignment to hs37d5? Since the secondary alignment itself is now filtered by VariantBam, the issue is with the primary that just lists in the SA tag that it has a secondary alignment? 

A simple solution would be to pipe the output of VariantBam (as plaintext stdout) through "grep -v hs37d5" and then to samtools to write the BAM. The issue then is that Manta will probably complain that the pair-mates of those reads are now missing their mate...

Unfortunately, filtering both pair-mates based on a tag present in only one of the mates cannot be done with a one-pass solution. VariantBam is able to filter out pair-mates in one pass only because the pair-mate alignment info is stored in the alignment. However, reads don't store their pair-mates SA tags, so VariantBam won't know which read pairs to filter until it finishes the entire BAM pass. 

If Manta is that picky though, I think a two-pass is the only solution. It would be something like:

Pass 1: ``samtools view <bam> | grep hs37d5 | cut -f1 > filter.list`` ## this gives the names of all read pairs that contain decoy alignments, tags, etc
Pass 2: ``samtools view -h <bam> | grep -F filter.list -v | samtools view - -hb > final.bam``

And then you don't actually use VariantBam, but you don't need to because a one-pass solution is impossible.

**Comment by naumenko-sa** [comment]
Hi Jeremiah @walaj !

Thanks so much for the response! 

Finally,
```
$VARIANT_BAM_PATH/variant $bam -L grch37d5.decoy.bed -v | grep -v hs37d5 | grep -v NC_007605 | samtools view - -hb > $bname.no_decoy_reads.bam
```
works for manta/lumpy/wham/cnvkit. I had to filter against both contig names in the decoy: hg37d5 and NC_007605.

Sergey
