### ISSUE TITLE
`-q` outputs no result

### ISSUE THREAD

**Issue by die4live** [jwalabroad/VariantBam#8]
I've tried the `--qc-file` argument with some combination of other args, but in output file, I only got a header 'ReadGroup       ReadCount       Supplementary   Unmapped        MateUnmapped    QCFailed        Duplicate       MappingQuality  NM      InsertSize      ClippedBases    MeanPhredScore  ReadLength' without stats.

Could there be an example for the usage of `-q`?

**Comment by walaj** [comment]
Thanks for noticing this. There was a bug where the qc-tracking got commented out. I have updated now. Also, Example 9 now contains a short example of using both the rule-counts flag (-c) and the qc flag (-q).

You may also notice that I overhauled the rules script to now use JSON instead of my custom brew that was becoming onerous to parse. This also has the effect of removing the need for Boost in building. Do let me know if you have any trouble with the new version. Hopefully it should be easier now that rules scripts can be validated using jsonlint.com, and since I added a number of command-line shortcuts that should reduce the need to have to create the JSON script anyway, except for more complex rules combinations.
